german translation
VernissageApp/Vernissage pull request #99
Opened 2023-11-22 10:08 UTC by tobybaier

all strings are translated, but I didn't add the localized file to the project yet. I hope there were no new strings since I started.

2023-11-29 22:33 UTC, PattaFeuFeu requested changes
Sorry for commenting here in German. I felt like it made most sense in this case. 😊 

I checked the translations and suggested some changes. Some are very much optional and are more “feeling-based”, others should probably be changed due to typos or outdated spelling.

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"global.error.canceledImageDownload" = "Laden der Bildes abgebrochen.";
```suggestion
"global.error.canceledImageDownload" = "Laden des Bildes abgebrochen.";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"global.error.errorDuringPurchaseVerification" = "Verifikation des Einkaufs fehlgeschlagen.";
Vielleicht eher „Einkauf konnte nicht verifiziert werden“?

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"home.title.allCaughtUp" = "Das war's, alles gesehen";
```suggestion
"home.title.allCaughtUp" = "Das war’s, alles gesehen";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"search.title.placeholder" = "Suche...";
```suggestion
"search.title.placeholder" = "Suche …";
```

Sollte eher mit Ellipse (U+2026) gesetzt und im Deutschen mit Leerzeichen davor gezeigt werden.

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"tags.navigationBar.followedTitle" = "Hashtags denen Du folgst";
```suggestion
"tags.navigationBar.followedTitle" = "Hashtags, denen Du folgst";
```

Nicht ganz sicher 🤔

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"userProfile.title.followedTags" = "Hashtags denen Du folgst";
```suggestion
"userProfile.title.followedTags" = "Hashtags, denen Du folgst";
```

Nicht ganz sicher 🤔

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"userProfile.title.following" = "Leute denen Du folgst";
```suggestion
"userProfile.title.followers" = "Leute, die Dir folgen";
"userProfile.title.following" = "Leute, denen Du folgst";
```

Nicht ganz sicher 🤔

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"userProfile.title.joined" = "%@ beigetreten";
Wird das in einem Datumskontext benutzt? Dann vielleicht lieber

```suggestion
"userProfile.title.joined" = "Am %@ beigetreten";
```

oder

```suggestion
"userProfile.title.joined" = "Beigetreten: %@ ";
```

?

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"userProfile.error.relationship" = "Beziehungsaktion fehlgeschlagen.";
Haha, was eine skurrile Übersetzung. 😁 Zu _Relationship action failed_ fällt mir gerade aber auch nichts besseres ein. Ist hoffentlich aus dem Kontext klar.

https://github.com/VernissageApp/Vernissage/blob/42795333718b9ff78eb3d94d00d4d66a9a9ac738/Vernissage/Views/UserProfileView/Subviews/UserProfileHeaderView.swift#L181-L192

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"notifications.error.loadingNotificationsFailed" = "Benachrichtigungen laden fehlgeschlagen.";
```suggestion
"notifications.error.loadingNotificationsFailed" = "Benachrichtigungen konnten nicht geladen werden.";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"compose.title.attachPhotoFull" = "Füge ein Foto hinzu und beschreibe was Du denkst.";
```suggestion
"compose.title.attachPhotoFull" = "Füge ein Foto hinzu und beschreibe, was Du denkst.";
```

Nicht ganz sicher 🤔

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"compose.title.photos" = "Foto Bibliothek";
```suggestion
"compose.title.photos" = "Fotobibliothek";
```

```suggestion
"compose.title.photos" = "Fotogalerie";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"photoEdit.navigationBar.title" = "Foto Details";
```suggestion
"photoEdit.navigationBar.title" = "Fotodetails";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"compose.title.missingAltTexts" = "Fehlende ALT Texte";
```suggestion
"compose.title.missingAltTexts" = "Fehlende ALT-Texte";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"placeSelector.title.search" = "Suchen...";
```suggestion
"placeSelector.title.search" = "Suchen …";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"placeSelector.error.loadingPlacesFailed" = "Benachrichtigungen laden fehlgeschlagen.";
```suggestion
"placeSelector.error.loadingPlacesFailed" = "Benachrichtigungen konnten nicht geladen werden.";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"settings.title.thankYouTitle" = "Dankeschön 💕";
```suggestion
"settings.title.thankYouTitle" = "Danke schön 💕";
```

Klingt komisch, ist aber so. 🙈

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"settings.title.thankYouMessage" = "Danke für die Unterstützung! Kleine und große Einkäufe helfen uns, unseren Traum eines hochqualitativen Produktes für unsere Nutzer aufrecht zu halten. Wir hoffen
```suggestion
"settings.title.thankYouMessage" = "Danke für die Unterstützung! Kleine und große Einkäufe helfen uns, unseren Traum eines hochqualitativen Produkts für unsere Nutzer aufrecht zu erhalten. Wir hoffen, Du liebst Vernissage!";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"settings.title.hapticsTabSelection" = "Tab Auswahl";
```suggestion
"settings.title.hapticsTabSelection" = "Tabauswahl";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"settings.title.alwaysShowAltDescription" = "Alternativen Text in der Detailansicht anzeigen";
Weiter oben hast Du noch „ALT-Text“ genutzt. Ich habe das Gefühl, dass sich die Benennung durchgesetzt hat. Vielleicht dann hier lieber auch 

```suggestion
"settings.title.alwaysShowAltTitle" = "ALT-Text anzeigen";
"settings.title.alwaysShowAltDescription" = "ALT-Text in der Detailansicht anzeigen";
```
?

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"settings.title.applicationIcon" = "Anwendungs-Icon";
```suggestion
"settings.title.applicationIcon" = "App-Icon";
```

oder

```suggestion
"settings.title.applicationIcon" = "App-Symbol";
```

Ich denke, „App“ ist inzwischen geläufig genug und wird von „Normalos“ häufiger verwendet als _Anwendung_.

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"settings.title.showAltText" = "ALT Icon anzeigen";
```suggestion
"settings.title.showAltText" = "ALT-Icon anzeigen";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"settings.title.showAltTextOnTimeline" = "ALT Icons werden in der Zeitleiste angezeigt";
```suggestion
"settings.title.showAltTextOnTimeline" = "ALT-Icons werden in der Zeitleiste angezeigt";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"settings.title.warnAboutMissingAltTitle" = "Warne mich bei fehlenden ALT Texten";
```suggestion
"settings.title.warnAboutMissingAltTitle" = "Warne mich bei fehlenden ALT-Texten";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"settings.title.warnAboutMissingAltDescription" = "Eine Warnung wird bei fehlenden ALT Texten angezeigt bevor ein Beitrag veröffentlicht wird.";
```suggestion
"settings.title.warnAboutMissingAltDescription" = "Vernissage wird Dich warnen, wenn Du einen Beitrag mit fehlendem ALT-Text veröffentlichen möchtest.";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"signin.title.serverAddress" = "Server Adresse";
```suggestion
"signin.title.serverAddress" = "Serveradresse";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"signin.title.enterServerAddress" = "Server Adresse eingeben";
```suggestion
"signin.title.enterServerAddress" = "Serveradresse eingeben";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"signin.title.chooseServer" = "oder wähle einen Pixelfed Server";
```suggestion
"signin.title.chooseServer" = "oder wähle einen Pixelfed-Server";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"status.title.via" = "via %@";
Vielleicht

```suggestion
"status.title.via" = "über %@";
```

?

Wobei ich auch „via“ in Ordnung finde.

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"status.title.reboostedBy" = "Boosted by";
```suggestion
"status.title.reboostedBy" = "Geboostet von";
```
oder

```suggestion
"status.title.reboostedBy" = "Boosted durch";
```
?

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"status.title.reboosted" = "Boosted";
```suggestion
"status.title.reboosted" = "Geboostet";
```

Nicht ganz sicher, wie sehr ich das Wort eindeutschen möchte …

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"status.title.unreboosted" = "Boot rückgängig gemacht";
```suggestion
"status.title.unreboosted" = "Boost rückgängig gemacht";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"status.title.reboost" = "Boost";
```suggestion
"status.title.reboost" = "Boosten";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"status.title.unreboost" = "Boost rückgängig machen";
```suggestion
"status.title.unreboost" = "Nicht mehr boosten";
```

Vielleicht? Wobei ich Deine Variante auch mag.

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"status.error.loadingStatusFailed" = "Beitrag laden fehlgeschlagen.";
```suggestion
"status.error.loadingStatusFailed" = "Konnte Beitrag nicht laden.";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"accounts.navigationBar.followers" = "Folgende";
Ich weiß, schwieriges Thema. Was hältst du von

```suggestion
"accounts.navigationBar.followers" = "Folgen";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"accounts.navigationBar.following" = "Folge";
```suggestion
"accounts.navigationBar.following" = "Gefolgt";
```
, ggf.

```suggestion
"accounts.navigationBar.following" = "Gefolgt von";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"accounts.navigationBar.reboostedBy" = "Boosted";
```suggestion
"accounts.navigationBar.reboostedBy" = "Geboostet von";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"accounts.navigationBar.favouritedBy" = "Favorisiert";
```suggestion
"accounts.navigationBar.favouritedBy" = "Favorisiert von";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"accounts.error.loadingAccountsFailed" = "Benutzer laden fehlgeschlagen.";
```suggestion
"accounts.error.loadingAccountsFailed" = "Konnte Benutzer nicht laden.";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"widget.title.qrCodeDescription" = "Widget mit QR Code zu Deinem Pixelfed Profil.";
```suggestion
"widget.title.qrCodeDescription" = "Widget mit QR-Code zu Deinem Pixelfed-Profil.";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"editProfile.title.privateAccountInfo" = "Wenn Dein Account privat ist, können nur Nutzer die Du bestätigst Deine Fotos und Videos auf Pixelfed sehen. Benutzer die Dir jetzt schon folgen sind nicht b
```suggestion
"editProfile.title.privateAccountInfo" = "Wenn Dein Account privat ist, können nur Nutzer die Du bestätigst Deine Fotos und Videos auf Pixelfed sehen. Benutzer, die Dir jetzt schon folgen, sind nicht betroffen.";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"editProfile.error.saveAccountFailed" = "Profil speichern fehlgeschlagen.";
```suggestion
"editProfile.error.saveAccountFailed" = "Konnte Profil nicht speichern.";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"editProfile.error.loadingAvatarFailed" = "Avatar laden fehlgeschlagen.";
```suggestion
"editProfile.error.loadingAvatarFailed" = "Konnte Avatar nicht laden.";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"instance.title.instanceInfo" = "Instanz Info";
```suggestion
"instance.title.instanceInfo" = "Instanzinfo";
```

2023-11-29 22:33 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"instance.title.email" = "Email";
```suggestion
"instance.title.email" = "E-Mail";
```

2023-11-30 07:23 UTC, tobybaier commented on Localization/de_DE.lproj/Localizable.strings
> +"settings.title.thankYouTitle" = "Dankeschön 💕";
uh, echt?

2023-11-30 07:29 UTC, tobybaier commented on Localization/de_DE.lproj/Localizable.strings
> +"status.title.unreboosted" = "Boot rückgängig gemacht";
Haha :) cool

2023-11-30 10:00 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"settings.title.thankYouTitle" = "Dankeschön 💕";
Jap. Es ist _Das Dankeschön_, aber _Danke schön_ zum Bedanken.

https://www.duden.de/rechtschreibung/danke

https://www.duden.de/rechtschreibung/Dankeschoen

2023-11-30 10:01 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"status.title.unreboosted" = "Boot rückgängig gemacht";
👢

2023-12-01 13:57 UTC, PattaFeuFeu commented on Localization/de_DE.lproj/Localizable.strings
> +"settings.title.thirdParty" = "Dritthersteller";
Das klingt mir sehr gut! 👍 Gute Wahl

2023-12-01 14:53 UTC, PattaFeuFeu approved these changes
🚀

2023-12-01 20:37 UTC, merged